### ISSUE TITLE
Type Errors with `sift`

### ISSUE THREAD

**Issue by artisonian** [denoland/deploy_examples#16]
When I run `check` on the **YAUS** example, I'm getting the following errors:

```sh
❱ deployctl check --libs=ns,fetchevent https://raw.githubusercontent.com/denoland/deploy_examples/main/yaus/mod.tsx
Check data:application/typescript;base64,aW1wb3J0IHR5cGUge30gZnJvbSAiZmlsZTovLy9Vc2Vycy9sY2FtcGJlbGwvTGlicmFyeS9DYWNoZXMvZGVuby9odHRwcy9kZW5vLmxhbmQvZWZkODZiZDc5YjUzNDUzOTlhYzI3YzQyNGE2NzgzYjM4NmZjODIxNzYyODYzYTVkOTc1M2YzYzRiNjVkOGQ3Ny50cyI7aW1wb3J0IHR5cGUge30gZnJvbSAiZmlsZTovLy9Vc2Vycy9sY2FtcGJlbGwvTGlicmFyeS9DYWNoZXMvZGVuby9odHRwcy9kZW5vLmxhbmQvOGE3YzI3ZGQ5Y2NkYWVhNjhkMTM2MjRjMGU0YjZkMTBlZjUxODlhNWU3YzI4YzczMWM4ZmExNTI5MGU3Y2FlMC50cyI7aW1wb3J0ICJodHRwczovL3Jhdy5naXRodWJ1c2VyY29udGVudC5jb20vZGVub2xhbmQvZGVwbG95X2V4YW1wbGVzL21haW4veWF1cy9tb2QudHN4Ijs=
error: TS2339 [ERROR]: Property 'entries' does not exist on type 'Headers'.
    headers: Object.fromEntries(req.headers.entries()),
                                            ~~~~~~~
    at https://deno.land/x/httpcache@0.1.0/mod.ts:6:45

TS2339 [ERROR]: Property 'entries' does not exist on type 'Headers'.
    const headers = Object.fromEntries(response.headers.entries());
                                                        ~~~~~~~
    at https://deno.land/x/httpcache@0.1.0/mod.ts:57:57

TS2339 [ERROR]: Property 'keys' does not exist on type 'URLSearchParams'.
    for (const param of searchParams.keys()) {
                                     ~~~~
    at https://deno.land/x/sift@0.1.6/mod.ts:206:38

TS2339 [ERROR]: Property 'keys' does not exist on type 'Headers'.
    for (const header of request.headers.keys()) {
                                         ~~~~
    at https://deno.land/x/sift@0.1.6/mod.ts:229:42

Found 4 errors.
```

**Comment by crqra** [comment]
@kt3k is any information related to this issue available in the documentation website?

**Comment by satyarohith** [comment]
@artisonian Thanks for opening the issue. The type errors are now resolved.
